import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.scss";
import Header from "@/components/header";

const bevietnam = Be_Vietnam_Pro({ weight:["500","800"], subsets:["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bevietnam.className}>
        <Header/>
        {children} 
      </body>
    </html>
  );
}
